### PR TITLE
Close the UI on swipe down and Script to run the example project

### LINKED ISSUE #36: Close the UI on swipe down
The expected user action when swiping down from the top of the modal (bottom sheet) is for the popup to close. 

This does not currently happen.

### PR DESCRIPTION
**Pull request by MiroBenicio**
- Fix the UI to close after a swipe down. It uses a vue composable, and has a verification of direction and pixels.
closes #36 
- Also add a script to run the example project, can be used in root folder to build and go to example folder, so its build and run capacitor android emulator.

### CODE REVIEW

**Comment by MiroBenicio** [comment]
[Screen_recording_20230810_095115.webm](https://github.com/tiki-bar/tiki-receipt-capacitor/assets/96149507/8f018c2f-7eb8-40b6-a8b2-3dfdbd6f39b0)

**Comment by MiroBenicio** [comment]
@mike-audi 

fix the buttons, now its fine.

**Review by ricardobrg — APPROVED** [review]

**Review by mike-audi — CHANGES_REQUESTED** [review]
The swipe down no longer works on my android device.

**Comment by MiroBenicio** [comment]
Tried another library to solve it!

by the way, in the video is that effect/fade/transition inttended ?
@mike-audi 
[Screen_recording_20230810_193852.webm](https://github.com/tiki-bar/tiki-receipt-capacitor/assets/96149507/9f606a6b-6180-41c2-9c29-bfed7375eeaf)

**Pull request merged**
